[tool.poetry]
name = "image2latex-app"
version = "0.1.0"
description = ""
authors = ["dohoanggiahuy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
